/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MapRouteImport } from './routes/map'
import { Route as LandlordRouteImport } from './routes/landlord'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as OwnerNewRouteImport } from './routes/owner.new'
import { Route as OwnerMessagesRouteImport } from './routes/owner.messages'
import { Route as OwnerMaintenanceRouteImport } from './routes/owner.maintenance'
import { Route as OwnerFinancesRouteImport } from './routes/owner.finances'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as LandlordNewRouteImport } from './routes/landlord.new'
import { Route as LandlordListingsRouteImport } from './routes/landlord.listings'
import { Route as LandlordInsightsRouteImport } from './routes/landlord.insights'
import { Route as LandlordInquiriesRouteImport } from './routes/landlord.inquiries'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as AdminRoleRequestsRouteImport } from './routes/admin.role-requests'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerNewRoute = OwnerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMessagesRoute = OwnerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMaintenanceRoute = OwnerMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerFinancesRoute = OwnerFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => OwnerRoute,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordNewRoute = LandlordNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordListingsRoute = LandlordListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordInsightsRoute = LandlordInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordInquiriesRoute = LandlordInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => LandlordRoute,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const AdminRoleRequestsRoute = AdminRoleRequestsRouteImport.update({
  id: '/admin/role-requests',
  path: '/admin/role-requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/landlord': typeof LandlordRouteWithChildren
  '/map': typeof MapRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/role-requests': typeof AdminRoleRequestsRoute
  '/community/$id': typeof CommunityIdRoute
  '/landlord/inquiries': typeof LandlordInquiriesRoute
  '/landlord/insights': typeof LandlordInsightsRoute
  '/landlord/listings': typeof LandlordListingsRoute
  '/landlord/new': typeof LandlordNewRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/owner/finances': typeof OwnerFinancesRoute
  '/owner/maintenance': typeof OwnerMaintenanceRoute
  '/owner/messages': typeof OwnerMessagesRoute
  '/owner/new': typeof OwnerNewRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/landlord': typeof LandlordRouteWithChildren
  '/map': typeof MapRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/role-requests': typeof AdminRoleRequestsRoute
  '/community/$id': typeof CommunityIdRoute
  '/landlord/inquiries': typeof LandlordInquiriesRoute
  '/landlord/insights': typeof LandlordInsightsRoute
  '/landlord/listings': typeof LandlordListingsRoute
  '/landlord/new': typeof LandlordNewRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/owner/finances': typeof OwnerFinancesRoute
  '/owner/maintenance': typeof OwnerMaintenanceRoute
  '/owner/messages': typeof OwnerMessagesRoute
  '/owner/new': typeof OwnerNewRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/landlord': typeof LandlordRouteWithChildren
  '/map': typeof MapRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/admin/role-requests': typeof AdminRoleRequestsRoute
  '/community/$id': typeof CommunityIdRoute
  '/landlord/inquiries': typeof LandlordInquiriesRoute
  '/landlord/insights': typeof LandlordInsightsRoute
  '/landlord/listings': typeof LandlordListingsRoute
  '/landlord/new': typeof LandlordNewRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/owner/finances': typeof OwnerFinancesRoute
  '/owner/maintenance': typeof OwnerMaintenanceRoute
  '/owner/messages': typeof OwnerMessagesRoute
  '/owner/new': typeof OwnerNewRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/community'
    | '/landlord'
    | '/map'
    | '/owner'
    | '/profile'
    | '/saved'
    | '/admin/role-requests'
    | '/community/$id'
    | '/landlord/inquiries'
    | '/landlord/insights'
    | '/landlord/listings'
    | '/landlord/new'
    | '/onboarding/role'
    | '/owner/finances'
    | '/owner/maintenance'
    | '/owner/messages'
    | '/owner/new'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/community'
    | '/landlord'
    | '/map'
    | '/owner'
    | '/profile'
    | '/saved'
    | '/admin/role-requests'
    | '/community/$id'
    | '/landlord/inquiries'
    | '/landlord/insights'
    | '/landlord/listings'
    | '/landlord/new'
    | '/onboarding/role'
    | '/owner/finances'
    | '/owner/maintenance'
    | '/owner/messages'
    | '/owner/new'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/community'
    | '/landlord'
    | '/map'
    | '/owner'
    | '/profile'
    | '/saved'
    | '/admin/role-requests'
    | '/community/$id'
    | '/landlord/inquiries'
    | '/landlord/insights'
    | '/landlord/listings'
    | '/landlord/new'
    | '/onboarding/role'
    | '/owner/finances'
    | '/owner/maintenance'
    | '/owner/messages'
    | '/owner/new'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  LandlordRoute: typeof LandlordRouteWithChildren
  MapRoute: typeof MapRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  AdminRoleRequestsRoute: typeof AdminRoleRequestsRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord': {
      id: '/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/new': {
      id: '/owner/new'
      path: '/new'
      fullPath: '/owner/new'
      preLoaderRoute: typeof OwnerNewRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/messages': {
      id: '/owner/messages'
      path: '/messages'
      fullPath: '/owner/messages'
      preLoaderRoute: typeof OwnerMessagesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/maintenance': {
      id: '/owner/maintenance'
      path: '/maintenance'
      fullPath: '/owner/maintenance'
      preLoaderRoute: typeof OwnerMaintenanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/finances': {
      id: '/owner/finances'
      path: '/finances'
      fullPath: '/owner/finances'
      preLoaderRoute: typeof OwnerFinancesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/new': {
      id: '/landlord/new'
      path: '/new'
      fullPath: '/landlord/new'
      preLoaderRoute: typeof LandlordNewRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/landlord/listings': {
      id: '/landlord/listings'
      path: '/listings'
      fullPath: '/landlord/listings'
      preLoaderRoute: typeof LandlordListingsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/landlord/insights': {
      id: '/landlord/insights'
      path: '/insights'
      fullPath: '/landlord/insights'
      preLoaderRoute: typeof LandlordInsightsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/landlord/inquiries': {
      id: '/landlord/inquiries'
      path: '/inquiries'
      fullPath: '/landlord/inquiries'
      preLoaderRoute: typeof LandlordInquiriesRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/admin/role-requests': {
      id: '/admin/role-requests'
      path: '/admin/role-requests'
      fullPath: '/admin/role-requests'
      preLoaderRoute: typeof AdminRoleRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface LandlordRouteChildren {
  LandlordInquiriesRoute: typeof LandlordInquiriesRoute
  LandlordInsightsRoute: typeof LandlordInsightsRoute
  LandlordListingsRoute: typeof LandlordListingsRoute
  LandlordNewRoute: typeof LandlordNewRoute
}

const LandlordRouteChildren: LandlordRouteChildren = {
  LandlordInquiriesRoute: LandlordInquiriesRoute,
  LandlordInsightsRoute: LandlordInsightsRoute,
  LandlordListingsRoute: LandlordListingsRoute,
  LandlordNewRoute: LandlordNewRoute,
}

const LandlordRouteWithChildren = LandlordRoute._addFileChildren(
  LandlordRouteChildren,
)

interface OwnerRouteChildren {
  OwnerFinancesRoute: typeof OwnerFinancesRoute
  OwnerMaintenanceRoute: typeof OwnerMaintenanceRoute
  OwnerMessagesRoute: typeof OwnerMessagesRoute
  OwnerNewRoute: typeof OwnerNewRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerFinancesRoute: OwnerFinancesRoute,
  OwnerMaintenanceRoute: OwnerMaintenanceRoute,
  OwnerMessagesRoute: OwnerMessagesRoute,
  OwnerNewRoute: OwnerNewRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRouteWithChildren,
  LandlordRoute: LandlordRouteWithChildren,
  MapRoute: MapRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  AdminRoleRequestsRoute: AdminRoleRequestsRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
